/********************************** (C) COPYRIGHT *******************************
* File Name          :Compound_Dev.C											*	
* Author             :                                                      *
* Version            :                                                    *
* Date               :                                             *
* Description        :                   *
********************************************************************************/

#ifndef	__COMPOUND_H__
#define __COMPOUND_H__

extern UINT16I 	TouchKeyButton;	

extern	void 	USBDeviceInit();
extern	void 	HIDValueHandle();
	
#endif
/**************************** END *************************************/
